// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: user_notes.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserNoteGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserNoteGroupsRequest) Reset() {
	*x = GetUserNoteGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_notes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserNoteGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNoteGroupsRequest) ProtoMessage() {}

func (x *GetUserNoteGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_notes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNoteGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetUserNoteGroupsRequest) Descriptor() ([]byte, []int) {
	return file_user_notes_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserNoteGroupsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserNoteGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserNoteGroups []*UserNoteGroup `protobuf:"bytes,1,rep,name=user_note_groups,json=userNoteGroups,proto3" json:"user_note_groups,omitempty"`
}

func (x *GetUserNoteGroupsResponse) Reset() {
	*x = GetUserNoteGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_notes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserNoteGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNoteGroupsResponse) ProtoMessage() {}

func (x *GetUserNoteGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_notes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNoteGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetUserNoteGroupsResponse) Descriptor() ([]byte, []int) {
	return file_user_notes_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserNoteGroupsResponse) GetUserNoteGroups() []*UserNoteGroup {
	if x != nil {
		return x.UserNoteGroups
	}
	return nil
}

type DeleteUserNoteGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DeleteUserNoteGroupRequest) Reset() {
	*x = DeleteUserNoteGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_notes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserNoteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserNoteGroupRequest) ProtoMessage() {}

func (x *DeleteUserNoteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_notes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserNoteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserNoteGroupRequest) Descriptor() ([]byte, []int) {
	return file_user_notes_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteUserNoteGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserNoteGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteUserNoteGroupResponse) Reset() {
	*x = DeleteUserNoteGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_notes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserNoteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserNoteGroupResponse) ProtoMessage() {}

func (x *DeleteUserNoteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_notes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserNoteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserNoteGroupResponse) Descriptor() ([]byte, []int) {
	return file_user_notes_proto_rawDescGZIP(), []int{3}
}

type UserNoteGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteGroupId string `protobuf:"bytes,2,opt,name=note_group_id,json=noteGroupId,proto3" json:"note_group_id,omitempty"`
}

func (x *UserNoteGroup) Reset() {
	*x = UserNoteGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_notes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserNoteGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNoteGroup) ProtoMessage() {}

func (x *UserNoteGroup) ProtoReflect() protoreflect.Message {
	mi := &file_user_notes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNoteGroup.ProtoReflect.Descriptor instead.
func (*UserNoteGroup) Descriptor() ([]byte, []int) {
	return file_user_notes_proto_rawDescGZIP(), []int{4}
}

func (x *UserNoteGroup) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserNoteGroup) GetNoteGroupId() string {
	if x != nil {
		return x.NoteGroupId
	}
	return ""
}

var File_user_notes_proto protoreflect.FileDescriptor

var file_user_notes_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x73, 0x68, 0x61, 0x72, 0x65, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x22, 0x33, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x6f, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x66, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e,
	0x6f, 0x74, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x22, 0x35, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x6f, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x1d, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4c, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x6f, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x6f, 0x74, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x64, 0x32, 0xf6, 0x01, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f,
	0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x6e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x2a, 0x2e,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x74, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x2c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b,
	0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_user_notes_proto_rawDescOnce sync.Once
	file_user_notes_proto_rawDescData = file_user_notes_proto_rawDesc
)

func file_user_notes_proto_rawDescGZIP() []byte {
	file_user_notes_proto_rawDescOnce.Do(func() {
		file_user_notes_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_notes_proto_rawDescData)
	})
	return file_user_notes_proto_rawDescData
}

var file_user_notes_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_notes_proto_goTypes = []interface{}{
	(*GetUserNoteGroupsRequest)(nil),    // 0: sharenote.schema.GetUserNoteGroupsRequest
	(*GetUserNoteGroupsResponse)(nil),   // 1: sharenote.schema.GetUserNoteGroupsResponse
	(*DeleteUserNoteGroupRequest)(nil),  // 2: sharenote.schema.DeleteUserNoteGroupRequest
	(*DeleteUserNoteGroupResponse)(nil), // 3: sharenote.schema.DeleteUserNoteGroupResponse
	(*UserNoteGroup)(nil),               // 4: sharenote.schema.UserNoteGroup
}
var file_user_notes_proto_depIdxs = []int32{
	4, // 0: sharenote.schema.GetUserNoteGroupsResponse.user_note_groups:type_name -> sharenote.schema.UserNoteGroup
	0, // 1: sharenote.schema.UserNoteGroups.GetUserNoteGroups:input_type -> sharenote.schema.GetUserNoteGroupsRequest
	2, // 2: sharenote.schema.UserNoteGroups.DeleteUserNoteGroup:input_type -> sharenote.schema.DeleteUserNoteGroupRequest
	1, // 3: sharenote.schema.UserNoteGroups.GetUserNoteGroups:output_type -> sharenote.schema.GetUserNoteGroupsResponse
	3, // 4: sharenote.schema.UserNoteGroups.DeleteUserNoteGroup:output_type -> sharenote.schema.DeleteUserNoteGroupResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_notes_proto_init() }
func file_user_notes_proto_init() {
	if File_user_notes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_notes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserNoteGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_notes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserNoteGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_notes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserNoteGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_notes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserNoteGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_notes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserNoteGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_notes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_notes_proto_goTypes,
		DependencyIndexes: file_user_notes_proto_depIdxs,
		MessageInfos:      file_user_notes_proto_msgTypes,
	}.Build()
	File_user_notes_proto = out.File
	file_user_notes_proto_rawDesc = nil
	file_user_notes_proto_goTypes = nil
	file_user_notes_proto_depIdxs = nil
}
